version: '3'

tasks:
  install:
    desc: Install project dependencies
    cmds:
      - npm install

  dev:
    desc: Run the development server locally
    deps: [install]
    cmds:
      - npm run dev

  build:
    desc: Build the project
    deps: [install, type-check]
    cmds:
      - npm run build

  type-check:
    desc: Run TypeScript type checking
    deps: [install]
    cmds:
      - npm run type-check

  lint:
    desc: Run ESLint
    deps: [install]
    cmds:
      - npm run lint

  preview:
    desc: Preview the production build locally
    deps: [build]
    cmds:
      - npm run preview

  validate:
    desc: Run all validations (type-check, lint)
    deps: [type-check, lint]

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf dist
      - rm -rf node_modules 